name: Deploy to Azure Web App

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Debug directory structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Repository contents:"
          ls -la

      - name: Install dependencies
        run: |
          echo "Moving to backend directory"
          cd quickhiresl_backend_expressjs
          echo "Backend directory contents:"
          ls -la
          echo "Installing dependencies..."
          npm install

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-app-name" # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: quickhiresl_backend_expressjs
