name: Deploy to Azure Web App

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Debug directory
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Backend directory contents:"
          ls -la quickhiresl_backend_expressjs

      - name: npm install
        working-directory: ${{ github.workspace }}/quickhiresl_backend_expressjs
        run: |
          echo "Installing dependencies in $(pwd)"
          npm install

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-app-name" # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/quickhiresl_backend_expressjs
