name: Deploy to Azure Web App

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Debug directory
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          cd ..
          echo "Parent directory contents:"
          ls -la

      - name: Install dependencies and start app
        run: |
          cd quickhiresl_backend_expressjs
          echo "Installing dependencies in $(pwd)"
          npm install
          echo "Starting application..."
          node app.js

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-app-name" # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: quickhiresl_backend_expressjs
