name: Deploy to Azure Web App

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Debug directory structure
        run: |
          echo "Current working directory:"
          pwd
          echo "List all files including hidden:"
          ls -la
          echo "Full directory tree:"
          tree -a

      - name: Move to correct directory and install
        run: |
          # Check if we're already in the backend directory
          if [ -f "package.json" ]; then
            echo "Already in backend directory"
          else
            echo "Moving to backend directory"
            cd $GITHUB_WORKSPACE/quickhiresl_backend_expressjs
          fi
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          npm install

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-app-name" # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: $GITHUB_WORKSPACE/quickhiresl_backend_expressjs
