name: quickhiresl_frontend
description: QuickHireSL Frontend Application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.4
  http_parser: ^4.0.2
  shared_preferences: ^2.5.1
  provider: ^6.1.1
  intl: ^0.19.0  # Downgraded to be compatible with flutter_localizations
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# Run this command to generate icons: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/quickhirelogo.jpg"
  adaptive_icon_background: "#98C9C5" # Light teal background color
  adaptive_icon_foreground: "assets/quickhirelogo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/quickhirelogo.jpg
    - assets/quickhire_logo.png
    - assets/apple.png
    - assets/facebook.png
    - assets/google.png
