name: quickhiresl_frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0  # Latest version
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0  # Correct placement

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/quickhire_logo.png
